#!/bin/bash

function mainMenu (){

	ADVSEL=$(whiptail --title "Main Menu" --fb --menu "select options:" 15 60 4 \
		"1" "Option" \
		"2" "Option" \
		"3" "Option" 3>&1 1>&2 2>&3)

	case $ADVSEL in
		1)
			echo "Option 1"
			whiptail --title "Option 1" --msgbox "Enter your data base " 8 45 --inputbox 8 45 [] 
			;;


		2)
                         echo "Option 2"
                        whiptail --title "Option 2" --msgbox "Your choose 2" 8 45
                        ;;

		3)
                         echo "Option 3"
                        whiptail --title "Option 3" --msgbox "Your choose 3" 8 45
                        ;;


		esac
}

mainMenu
